### ISSUE TITLE
Dataset request: feature_comparison_NJP2023

### ISSUE THREAD

**Issue by jvita** [colabfit/data-lake#11]
# Contribute content

## Contributor/requester
> Contact information about the person contributing/requesting the data. Used for communication purposes.
​

**Name**:  Josh Vita
**Email**:  vita1@llnl.gov

## Dataset
> Any information necessary to help the ColabFit find and access the data, and to correctly cite relevant material. The "name" and "description" will be used when publishing to the ColabFit exchange, and should be human-readable. Author list should include full first names, unless the author is normally attributed by initials. Links should include relevant publications and online location of dataset, if available.

**Name**:  feature_comparison_NJP2023

**Authors**:  Ting Han, Jie Li, Liping Liu, Fengyu Li, Lin-Wang Wang

**Links**:  
*  Publication link: https://iopscience.iop.org/article/10.1088/1367-2630/acf2bb
*  Dataset link: contact authors

**Description**:  

## Calculations  
> Details regarding how the data was computed in order to improve reproducibility. Provide as much information as possible. Input files are highly encouraged. Additional details might include functional, basis set, energy cutoff, k-point grid, reference energy, etc.
​

**Method**: DFT
**Software**: Unknown
**Additional details**: Unknown
**Files**:  Unknown

### Included properties
> See [the current list of ColabFit property definitions](https://materials.colabfit.org/browse/property-definitions). If you believe your data does not match one of the existing definitions, then you must submit a new property definition following [the template provided in the examples folder](https://github.com/gpwolfe/colabfit-data/blob/main/examples/example_property_definitions.py).  

|   Name            |   Units   |   Notes   |
|   ---             |   ---     |   ---     |

  
## Configurations
> Basic information explaining the types of configurations in the dataset, and how they are organized.  
> Elements should be listed by chemical symbol

**Elements**:  C, S
**Number of configurations**:    about 18755 in the available files (directly hosted on GitHub)
**Storage format**: Unknown

### Naming convention
> If your configurations have names, please describe where their names can be found (e.g., as a field in an `ASE.Atoms.info` dictionary).
​

​
### Configuration sets
> Configuration sets are used to define a conceptual grouping over a collection of atomic configurations. Configuration sets are constructed via regex filtering on specified keys.
​

Paper contents suggest that configuration sets have been defined. However, this can't be verified without access to the data.

|Key|Regex|Description|
|---|---|---|

  
### Configuration labels
> Configuration labels can be attached to your data to improve interpretability. This is done via regex matching on specified keys.
​

Paper contents suggest that configuration labels may exist. However, this can't be verified without access to the data.

|Key|Regex|Label|
|---|---|---|

  
### Distribution License
>The license under which the content will be distributed (e.g. Creative Commons Zero)

Unknown

**Comment by jvita** [comment]
More notes that I took:

- Does Github have an option for "Open an issue using this MD file as a template"?
- We should be able to add tags like "missing information" or "contact author"
- We should track which institutions are contributing data. Maybe easier once we have something like "profiles" on ColabFit

**Comment by gpwolfe** [comment]
contacted corresponding author

**Comment by gpwolfe** [comment]
data link appears to be repaired.
base link: http://www.pwmat.com/mlff
DFT dataset(s) link: https://github.com/LonxunQuantum/PWMLFF_library
Parser may be adapted from https://github.com/LonxunQuantum/PWMLFF_library/blob/main/utils/MOVEMENT2xyz.py

A number of the splits of the dataset (split by element type and by number of images in the trajectory) are only available via download through baidu netdisk client. Others are prepared for ingest

**Comment by gpwolfe** [comment]
Data that is available directly on GitHub ingested. Data available pending creation of dataset files.
