### ISSUE TITLE
Dataset request: xxMD-CASSCF and xxMD-DFT

### ISSUE THREAD

**Issue by jvita** [colabfit/data-lake#12]
# Contribute content

## Contributor/requester
> Contact information about the person contributing/requesting the data. Used for communication purposes.
​

**Name**:  Josh Vita
**Email**:  vita1@llnl.gov

## Dataset
> Any information necessary to help the ColabFit find and access the data, and to correctly cite relevant material. The "name" and "description" will be used when publishing to the ColabFit exchange, and should be human-readable. Author list should include full first names, unless the author is normally attributed by initials. Links should include relevant publications and online location of dataset, if available.

**Name**:  xxMD-CASSCF, xxMD-DFT

**Authors**:  Zihan Pengmei, Junyu Liu, Yinan Shu

**Links**:  
*  Publication link: https://arxiv.org/abs/2308.11155
*  Dataset link: https://github.com/zpengmei/xxMD

**Description**:  
The xxMD (Extended Excited-state Molecular Dynamics) dataset is a comprehensive collection of non-adiabatic trajectories encompassing several photo-sensitive molecules. This dataset challenges existing Neural Force Field (NFF) models with broader nuclear configuration spaces that span reactant, transition state, product, and conical intersection regions, making it more chemically representative than its contemporaries.

## Calculations  
> Details regarding how the data was computed in order to improve reproducibility. Provide as much information as possible. Input files are highly encouraged. Additional details might include functional, basis set, energy cutoff, k-point grid, reference energy, etc.
​

**Method**: DFT, CASSCF
**Software**: Unknown
**Additional details**: M06 XC-functional
**Files**:  None

### Included properties
> See [the current list of ColabFit property definitions](https://materials.colabfit.org/browse/property-definitions). If you believe your data does not match one of the existing definitions, then you must submit a new property definition following [the template provided in the examples folder](https://github.com/gpwolfe/colabfit-data/blob/main/examples/example_property_definitions.py).

Note: it appears that they have computed the energies/forces for all of the configurations at two levels of theory.

|   Name            |   Units   |   Notes   |
|   ---             |   ---     |   ---     |
|   potential-energy |    Unknown     |     |
|   atomic-forces   |     Unknown      |           |
  
## Configurations
> Basic information explaining the types of configurations in the dataset, and how they are organized.  
> Elements should be listed by chemical symbol

**Elements**:  C, H, O, N
**Number of configurations**:    lots
**Storage format**: ASE?

### Naming convention
> If your configurations have names, please describe where their names can be found (e.g., as a field in an `ASE.Atoms.info` dictionary).
​

Names can be generated by assigning indices to the configurations, prepended with their full path. For example: `xxMD-DFT/sti/0`.
​
### Configuration sets
> Configuration sets are used to define a conceptual grouping over a collection of atomic configurations. Configuration sets are constructed via regex filtering on specified keys.
​

Data appears to be grouped into configuration sets, but I'm not yet sure what these correspond to.

|Key|Regex|Description|
|---|---|---|

  
### Configuration labels
> Configuration labels can be attached to your data to improve interpretability. This is done via regex matching on specified keys.
​

|Key|Regex|Label|
|---|---|---|

  
### Distribution License
>The license under which the content will be distributed (e.g. Creative Commons Zero)

[Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/legalcode)

**Comment by gpwolfe** [comment]
staged for ingest following next database update

**Comment by gpwolfe** [comment]
new database now live
