### ISSUE TITLE
Dataset request: AIMD-Chig

### ISSUE THREAD

**Issue by jvita** [colabfit/data-lake#17]
### Name

Josh Vita

### Email

vita1@llnl.gov

### Dataset name

AIMD-Chig

### Authors

Tong Wang, Xinheng He, Mingyu Li, Bin Shao, Tie-Yan Liu

### Links

* Publication: https://www.nature.com/articles/s41597-023-02465-9#Sec7
* Data: https://figshare.com/articles/dataset/_strong_AIMD-Chig_exploring_the_conformational_space_of_166-atom_protein_strong_em_strong_Chignolin_strong_em_strong_with_strong_em_strong_ab_initio_strong_em_strong_molecular_dynamics_strong_/22786730

### Dataset description

This dataset covers the conformational space of Chignolin with DFT-level precision. We sequentially applied replica exchange molecular dynamics (REMD), conventional MD, and ab initio MD (AIMD) simulations on a 10 amino acid protein, Chignolin, and finally collected unparalleled 2 million biomolecule structures with quantum level energy and force records.

### File details

Data repo includes README specifying folder contents/structure, which reports that the data is stored in XYZ format and is grouped by "anchor".

In total, looks to be ~15GB (zipped).

### Method

DFT

### Software

ORCA

### Software version(s)

4.2.1

### Additional details

M06-2X functional in conjunction with 6–31 G* basis set was employed for the calculation

### Property types

Atomic forces, Potential energy

### Property details

* potential-energy: units=Hartree, per-atom=False
* atomic-forces: units=Hartree/Ang

### Elements

Chignolin

### Number of Configurations

2,000,000

### Naming convention

Names can likely be generated by <sub_folder>/<anchor>/snapshot.xyz.

### Distribution license

CC BY 4.0

### Permissions

- [ ] I confirm that I have the necessary permissions to submit this dataset

**Comment by jvita** [comment]
Some notes for improving the upload template:
- The template should enable selecting molecule type, instead of only elements. I'm sure there's a tool out there somewhere from generating element lists from molecule names.
- CS construction should support pre-built groups better. For example, the data here is grouped as <sub_folder>/<anchor>; these should be automatically converted to CSs somehow. I didn't add CS definitions here because I didn't want to have to add 100 lines of regexes, one for each group.

**Comment by gpwolfe** [comment]
It looks like the subdirectories [0 - 99] in this case are just a way of dividing the 10K initial structures into manageable, 100-structure chunks. The actual divisions (by initial structure, or 'anchors', as defined in the text) are separated into the 10K individual files. Would that be an unreasonable number of configuration sets?

**Comment by jvita** [comment]
In that case, I'd say that it should be left as a single CS. Perhaps the anchors could be given as labels.

**Comment by gpwolfe** [comment]
Staged for ingest after next database update

**Comment by gpwolfe** [comment]
new database now live
