### ISSUE TITLE
[Dataset request]: **SPICE (Small-Molecule/Protein Interaction Chemical Energies)**

### ISSUE THREAD

**Issue by ipcamit** [colabfit/data-lake#22]
### Name

Amit Gupta

### Email

gupta839@umn.edu

### Dataset name

SPICE_2023

### Authors

Peter Eastman, Pavan Kumar Behara, David L. Dotson, Raimondas Galvelis, John E. Herr, Josh T. Horton, Yuezhi Mao, John D. Chodera, Benjamin P. Pritchard, Yuanqing Wang, Gianni De Fabritiis & Thomas E. Markland 

### Links

github repo: https://github.com/openmm/spice-dataset

Publication: https://www.nature.com/articles/s41597-022-01882-6

Actual data: https://zenodo.org/records/8222043

### Dataset description

SPICE (Small-Molecule/Protein Interaction Chemical Energies) is a collection of quantum mechanical data for training potential functions. The emphasis is particularly on simulating drug-like small molecules interacting with proteins.

### Method

DFT

### Method (other)

ωB97M-D3BJ

### Software

Psi4

### Additional details

Gaussian basis set: def2-TZVPPD

### Elements

H, Li, C, N, O, F, Na, Mg, P, S, Cl, K, Ca, Br, I

### Number of Configurations

1132808

### Distribution license

CC0

### Permissions

- [ ] I confirm that I have the necessary permissions to submit this dataset

**Comment by gpwolfe** [comment]
Spice is staged for ingestion following database update

**Comment by gpwolfe** [comment]
new database now live
