### ISSUE TITLE
[Dataset request] Matbench

### ISSUE THREAD

**Issue by smcantab** [colabfit/data-lake#33]
### Name

Stefano Martiniani

### Email

sm7683@nyu.edu

### Dataset name

matbench_*

### Authors

"Alexander Dunn", "Qi Wang", "Alex Ganose", "Daniel Dopp", "Anubhav Jain"

### Links

https://matbench.materialsproject.org/Benchmark%20Info/matbench_v0.1/
https://www.nature.com/articles/s41524-020-00406-3

### Dataset description

Matbench is an automated leaderboard for benchmarking state of the art ML algorithms predicting a diverse range of solid materials' properties. It is hosted and maintained by [the Materials Project](https://materialsproject.org/).

There are several datasets of potential interest for MLIP/DDIP development. Others contain properties that may not be of interest (frequency at last phonon, is-metal, bulk modulus)

matbench_mp_gap: band gap (eV); https://doi.org/10.1063/1.4812323
matbench_mp_e_form: formation energy (eV/atom); https://doi.org/10.1016/j.commatsci.2014.10.037
matbench_perovskites: formation energy per perovskite cell (eV); https://doi.org/10.1039/C2EE22341D

### File details

zipped json

### Software

None

### Permissions

- [X] I confirm that I have the necessary permissions to submit this dataset

**Comment by gpwolfe** [comment]
ingested to new db version, will remove upon update

**Comment by gpwolfe** [comment]
new database now live
