### ISSUE TITLE
[Dataset submission]: CrCoNi_Cao_2022

### ISSUE THREAD

**Issue by yifan-henry-cao** [colabfit/data-lake#55]
### Name

Yifan Cao

### Email

yifanc@mit.edu

### Dataset name

CrCoNi_Cao_2022

### Authors

Yifan Cao, Killian Sheriff, Rodrigo Freitas

### Publication link

https://arxiv.org/abs/2311.01545

### Data link

https://github.com/yifan-henry-cao/MachineLearningPotential/blob/main/Training_datasets/Training_Cao_20220823.cfg

### Additional links

https://github.com/yifan-henry-cao/MachineLearningPotential

### Dataset description

Training dataset that captures chemical short-range order in equiatomic CrCoNi medium-entropy alloy published with our work ``Quantifying chemical short-range order in metallic alloys``

### File details

1 compiled cfg file containing 1257 individual structures
Total size: 11MB

### Method

DFT

### Software

VASP

### Software version(s)

6.2.1

### Additional details

XC functional: Perdew–Burke–Ernzerhof
Basis set: projector-augmented wave
Plane wave cutoff: 430eV
K-point grid: 3 * 3 * 3

### Property types

Atomic forces, Potential energy

### Property details

Potential-energy: units=eV, per-atom=false
Atomic forces: units=eV/A, per-atom=True

### Elements

Cr, Co, Ni

### Number of Configurations

1257

### Permissions

- [X] I confirm that I have the necessary permissions to submit this dataset

**Comment by gpwolfe** [comment]
Hi Yifan,
We're just switching over to a more scalable database at the moment, but we're planning to continue ingests in the next couple of weeks. I'll contact you here if we have any questions on the data. Feel free to comment in this thread if you have any questions.

**Comment by gpwolfe** [comment]
Processed, available pending next db batch update

**Comment by gpwolfe** [comment]
Now ingested to ColabFit
